### ISSUE TITLE
Is it possible to register custom shortcodes?

### ISSUE THREAD

**Issue by BenParizek** [selvinortiz/craft.doxter#18]
I see a registerShortcodes method in the code but I don't see a registerShortcodes hook?

Is there a way to register a custom shortcode from another plugin?

**Comment by selvinortiz** [comment]
Shortcode registration is event driven and not hook driven. This allows Doxter to wait until the last second to load shortcodes. Instead of defining a method in your plugin, you listen for the before shortcode parsing event and then call **doxter()->registerShortcodes()**

You can see **DoxterPlugin::init()** for an example.
